### ISSUE TITLE
Index Error : list index out of range

### ISSUE THREAD

**Issue by athulmenon** [linzhi2013/MitoZ#106] opened 2021-01-13 10:58 UTC
Hi,
Thanks for this great tool.

I am running a docker container for Mitoz (v2.3). I am running using -all option as below.

`python3 /app/release_MitoZ_v2.3/MitoZ.py all --genetic_code 4 --outprefix Fusarium --thread_number 12 --fastq1 Illumina_R1_1.fastq.gz --fastq2 Illumina_R2_2.fastq.gz --fastq_read_length 150 --run_mode 2 --filter_taxa_method 3` 

But it stopped after running and generating some 4 files with the the below error.

`2021-01-13 10:35:10
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/bin/common/circle_check.py /project/tmp/Fusarium.assembly/work71.hmmout.fa work71 3

A: not found!
A: not found!
Traceback (most recent call last):
  File "/app/release_MitoZ_v2.3/MitoZ.py", line 2009, in <module>
    outprefix=args.outprefix)
  File "/app/release_MitoZ_v2.3/MitoZ.py", line 832, in assemble
    min_abundance=min_abundance)
  File "/app/release_MitoZ_v2.3/MitoZ.py", line 1102, in findmitoscaf
    cds_taxa_file = glob(prefix+'*.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds.taxa')[0]
IndexError: list index out of range
`

Can you please let me know why this has happened and to rectify this.

Thanks,
Athul

**Comment by linzhi2013** [comment] 2021-01-13 17:51
Hi Athul,

could you please check the file `work71.hmmout.fa` in the `tmp` directory, to see what's in this file?

If the file is empty, then there was no mt-sequences found.

**Comment by athulmenon** [comment] 2021-01-15 05:21
Hi linzhi,

Thank you for the reply.

The file have 2 contigs with a total size of 116kb. 

So are you suggesting to run the annotate and visualize modules separately on this result?

Regards,
Athul

**Comment by linzhi2013** [comment] 2021-01-15 09:08
what is the length of each contig? If both of them very long, or their seqids have `_FivePCGs` tag, then they are not considered as real mitogenomes. You can simply blast them against the online NCBI NT database and check what clades the contigs belong to.

**Comment by linzhi2013** [comment] 2021-01-21 16:21
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:21 UTC
