### ISSUE TITLE
questions using --run_ mode 3

### ISSUE THREAD

**Issue by paul-bio-hh** [linzhi2013/MitoZ#102] opened 2021-01-11 13:21 UTC
Hi Linzhi. Me again. With your help, I did get the result from circos.
Without you, I might be in trouble.... Thanks again.

As my data was produced by assemble --run_mode 2, I had 6 missing PCGs.
Therefore, I decided to do more analysis with --run_mode 3

everything was fine so far, but I have some question.

![image](https://user-images.githubusercontent.com/76936761/104183661-a741e900-5455-11eb-9b5d-eeec12f65118.png)
![image](https://user-images.githubusercontent.com/76936761/104183754-c80a3e80-5455-11eb-9b3b-f790c355c606.png)
![image](https://user-images.githubusercontent.com/76936761/104184824-68149780-5457-11eb-9b1d-d510175574bd.png)
those are the results from all2 (run mode 2)

In the circos result,
there were two scaffolds. Both of them had CYTB, COX2, ATP6,,,,. 
Do I have to choose one scaffold from work71.mitogenome.fa? 

here is code that i use for the all2 --run_mode 3

$MitoZ.py all2 --genetic_code 5 --clade Mollusca --outprefix O-2 --thread_number 32 --requiring_taxa 'Mollusca'
--fastq1 /0_2_S183_L004_R1_001_val_1.fq 
--fastq2 /0_2_S183_L004_R2_001_val_2.fq
--fastq_read_length 101 --insert_size 550 --run_mode 3 
--quick_mode_fa_genes_file work71.mitogenome.fa
--missing_PCGs ND1 ND2 ND3 ND4 ND4L ND5 ND6 tRNA-Ala tRNA-Trp 
--quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted
--quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.fa 

From all2 (--run_mode 2) do i have to choose one scaffold?

**Comment by linzhi2013** [comment] 2021-01-13 10:18
https://github.com/linzhi2013/MitoZ

![image](https://user-images.githubusercontent.com/6203542/104439136-1112dd80-5591-11eb-95f2-896a6c2955ac.png)

**Comment by linzhi2013** [comment] 2021-01-21 16:23
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:23 UTC
