### ISSUE TITLE
 No such file or directory:  'work71.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds'

### ISSUE THREAD

**Issue by karl1926** [linzhi2013/MitoZ#103] opened 2021-01-12 15:11 UTC
Hi,
I got the following error:

_run the genewise shell file
running genewise
convert result to gff3 format
cat: './work71.hmmtblout.besthit.sim.fa.genewise/*/*.genewise': File o directory non esistente
Sorry, the annotation finished with no result!
2021-01-12 14:51:11
rm -rf *.nhr *.nin *.nsq formatdb.log *.tblastn.shell *.length *.blast *.blast.filter *.shell *.blast.solar *.blast.solar.filter *.blast.solar.filter.table *.blast.solar.filter.table.nonredundance *.blast.solar.filter.nr *.genewise *.solar.genewise.gff *.solar.genewise.gff.cds

Traceback (most recent call last):
  File "/home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 336, in <module>
    requiring_taxa=args.requiring_taxa)
  File "/home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 198, in filter_taxa
    with open(cdspos, 'r') as fh, open(cdspos_taxa_log, 'w') as fh_taxalog:
FileNotFoundError: [Errno 2] No such file or directory: 'work71.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds'
Error occured when running command:
/opt/miniconda-4.5.1/envs/mitoz-env/bin/python3 /home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py -fa work71.hmmtblout.besthit.sim.fa -MTsoft /home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -db /home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/profiles/MT_database/Animal_CDS_protein.fa -thread 16 -genetic_code 5 -requiring_taxa 'Arthropoda' -relax 0 -WISECONFIGDIR /home/user/MITO/fastq/Fastq/release_MitoZ_v2.3/bin/annotate/wisecfg -outf work71.hmmtblout.besthit.sim.filtered.fa_

I saw a recent closed issue with a similar error where you suggested to use the Docker. I cannot use user-deployed containers  such as Docker or Singularity such as Docker or Singularity on the machine I am using. Do you have any other alternative or suggestion to fix the issue?

**Comment by linzhi2013** [comment] 2021-01-13 09:42
I saw the message `Sorry, the annotation finished with no result!`. It may be not a problem of MitoZ installation. 

Check how many sequences and their lengths in the `work71.hmmtblout.besthit.sim.fa` file, which contains the initial found candidate mt-sequences.

**Comment by karl1926** [comment] 2021-01-13 11:25
Hi linzhi, thanks for the reply. The file contains only two sequences of 117 nt each:

>C557 50.0
TTGTTATTTTTTATTTGCCCTGTCCGTGTGAGCTAACAGTCGTACTGGCTTTCATGGGAAACATGTATTTTTCGTGGTTGAAACCTTTTGGATTAACTGGTGCTAGAGTGATCAATA
>C557 50.0
TTGTTATTTTTTATTTGCCCTGTCCGTGTGAGCTAACAGTCGTACTGGCTTTCATGGGAAACATGTATTTTTCGTGGTTGAAACCTTTTGGATTAACTGGTGCTAGAGTGATCAATA
~

**Comment by linzhi2013** [comment] 2021-01-13 17:57
I see. So mt-assembly seems failed. 

Could:

(1) Try to use multiple kmer mode? Or you can run the `mitoAssemble` manually, in this way, you can try different kmers. then run `findmitoscaf`, `annotate` commands.
(2) Use more data if you have.

**Comment by linzhi2013** [comment] 2021-01-21 16:23
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:23 UTC
