### ISSUE TITLE
How to asemble MT genome of cnidarian?

### ISSUE THREAD

**Issue by lijunyuan** [linzhi2013/MitoZ#85] opened 2020-09-15 12:26 UTC
Here, My mitogenomes are from cnidarians (corals), among the assemble parameters, the --clade has so many options ("Chordata", "Arthropoda", "Echinodermata", "Annelida-segmented-worms", "Bryozoa", "Mollusca", "Nematoda", "Nemertea-ribbon-worms", "Porifera-sponges"), unfortunately, no cnidarian is listed in it, then which one should be selected in my situation? By the way, what about the --requiring_taxa, is it ok if it set the same with --clade ?

**Comment by linzhi2013** [comment] 2020-09-15 13:10
What kind of genetic code table cnidarian uses?

You can try to run MitoZ with  "Arthropoda":

1. Assemble nuclear + mt genome mixture will certainly work in any case.

2. searching for mitochondrial sequences possibly will also work, since we use HMM profile to filter out mt-sequenhces

3. PCG annotation  may have problems, if your species use a different genetic code table, which makes the translation wrong.

**Comment by linzhi2013** [comment] 2021-01-21 16:24
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:24 UTC
