### ISSUE TITLE
Multiple mitochondrial genomes in one library

### ISSUE THREAD

**Issue by francesconardi** [linzhi2013/MitoZ#63] opened 2020-04-22 16:21 UTC
I have a paired end library from a pool of nuclear+mitochondrial DNA from 10 different species. 
Is it possible to assemble them in MitoZ to obtain 10 (hopefully) different mitochondrial genomes, or is MitoZ working under the assumption that there is only one genome, and therefore discard the rest?
Thanks a lot in advance - Francesco

**Comment by linzhi2013** [comment] 2020-04-22 16:41
Hi Francesco,

MitoZ is designed for one species per sample. But you can still give it a try, since MitoZ will output all sequences with >= 5 PCGs.

Meanwhile, this paper from our group might be interesting to you: *Multiplex sequencing of pooled mitochondrial genomes—a crucial step toward biodiversity analysis using mito-metagenomics* (https://doi.org/10.1093/nar/gku917), though it is a bit old.

Cheers

**Comment by linzhi2013** [comment] 2021-01-21 16:27
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:27 UTC
