### ISSUE TITLE
如何实现线虫动物门的线粒体组拼接？

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#39] opened 2020-01-04 06:45 UTC
我尝试在MitoZ.py修改了
search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
choices=["Nematoda", "Arthropoda"]
但是还是不能完成拼接，请问还有什么地方需修改的？

**Comment by linzhi2013** [comment] 2020-01-05 14:56
> 我尝试在MitoZ.py修改了
> search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
> choices=["Nematoda", "Arthropoda"]
> 但是还是不能完成拼接，请问还有什么地方需修改的？

Hi zskysafe, could you please show me the log file? Or what was the error after you used "Nematoda" ?

thanks!

**Comment by zskysafe** [comment] 2020-01-07 06:46
I only modified this place in MitoZ.py
>>>
search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
	choices=["Nematoda", "Arthropoda"],
Run the following command
>>>
python3 MitoZ.py assemble --genetic_code 5 --clade Nematoda --outprefix $species \
--thread_number 12 \
--fastq1 $fq1 \
--fastq2 $fq1 \
--fastq_read_length 150 \
--insert_size 250 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Nematoda' 

>>>
Killed
Error occured when running command:
MitoZ_v2.4-nema/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12

**Comment by zskysafe** [comment] 2020-01-07 06:46
search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
&nbsp;&nbsp;&nbsp; choices=["Nematoda", "Arthropoda"],
&gt;&gt;&gt;
I only modified this place in MitoZ.py
Then ran the shell in the attachment





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Guanliang MENG"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月5日(星期天) 晚上10:56
收件人:&nbsp;"linzhi2013/MitoZ"<MitoZ@noreply.github.com&gt;;
抄送:&nbsp;"赵天佑"<962539075@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhi2013/MitoZ] 如何实现线虫动物门的线粒体组拼接？ (#39)



 
我尝试在MitoZ.py修改了
 search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
 choices=["Nematoda", "Arthropoda"]
 但是还是不能完成拼接，请问还有什么地方需修改的？
  
Hi zskysafe, could you please show me the log file? Or what was the error after you used "Nematoda" ?
 
thanks!

**Comment by linzhi2013** [comment] 2020-01-07 08:10
> MitoZ_v2.4-nema/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12

Hi zskysafe, 

Your job was killed (`MitoZ_v2.4-nema/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12`), this command has nothing to with what you did to the `MitoZ.py` file. I think the problem could be the input dataset is too large and thus used too much memory, then the command got killed. 

You can run this command alone in your terminal, e.g.

```
$ cd /to/somewhere/to/run/the/job
$ path/to/MitoZ_v2.4-nema/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12
```

and check if the command above will be killed?


possible solutions:

1. "enrich" the mitochondrial reads
2. use fewer thread number, e.g. `4`.

**Comment by linzhi2013** [comment] 2021-01-21 16:29
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:29 UTC
