### ISSUE TITLE
Program freezed at "Processed 1000 scaffolds"

### ISSUE THREAD

**Issue by dongzhang0725** [linzhi2013/MitoZ#95] opened 2020-12-22 07:33 UTC
Dear all,

I ran MitoZ with this command `python3 MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix output --thread_number 70 --fastq1 input_1.clean.fq.gz --fastq2 input_2.clean.fq.gz --fastq_read_length 150 --insert_size 250  --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Arthropoda' `, it only took 10 minutes going to the following step:
```
There are 1384 locis, which contain more than 2 contigs
The loci can be classified to four kinds:
LINEAR:1068
FORK:176
BUBBLE:11
COMPLEX:129
time spent on creating transcriptome 4s

Start to load reads for gap filling. 50 length discrepancy is allowed
...
Loaded 3525941 reads from work71.readInGap
70 thread created
...
Processed 1000 scaffolds
```
However, after two days, it still freezed at this step, is there some unforeseen problem? Need I wait for the program to finish?

**Comment by linzhi2013** [comment] 2020-12-22 08:43
Hi there,

You should stop it, it's running too long.

What's the total volume of your input Fastq files (not the file size). If too large volume (e.g. >8Gbp) provided, it's difficult for MitoZ to finish. 

You may show me the stderr and stdout logs, as possibly a screenshot of the "tmp" directory.

Cheers

**Comment by dongzhang0725** [comment] 2020-12-22 09:12
Hi @linzhi2013 ,

The volume of the two input fastq files is around 2G. The logs and screenshot are showing below:

![image](https://user-images.githubusercontent.com/15956921/102870624-3c197e00-4478-11eb-802e-99534b933581.png)

![image](https://user-images.githubusercontent.com/15956921/102870641-4471b900-4478-11eb-8b1a-904c14b7e1c2.png)

[logs.txt](https://github.com/linzhi2013/MitoZ/files/5728844/logs.txt)

**Comment by Prunoideae** [comment] 2020-12-22 10:28
A possible cause of this is because you specified `--thread 70`, similar to the issue #56.

The SOAPdenovo2 is not robust enough on such a highly paralleled environment, I guess there are things like dead-lock or some race problem just happened.

On my implementation of pipeline, this problem also occurs on scaffolding (though we use MEGAHIT as assembler, SOAPdenovo-fusion and SOAPdenovo-127mer is used for scaffolding), but after limiting the thread to scaffolding to no more than 16, it never stuck again.

**Comment by linzhi2013** [comment] 2020-12-22 10:46
Yes, this can be caused by too many threads are provided. Based on my experience, we've never used so many threads in any single bioinformatical program.

**Comment by linzhi2013** [comment] 2020-12-22 10:48
I've updated the `README.md` file to reflect this: https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/README.md#23-memory.

**Comment by dongzhang0725** [comment] 2020-12-22 12:07
Dear @linzhi2013 and @Prunoideae,

I changed the threads to 16, and it works perfectly.

Thank you very much, 

Dong

**Comment by linzhi2013** [comment] 2020-12-23 10:00
You're welcome.

I'm closing this. Feel free to create new issues if necessary.

Cheers

**Closed by linzhi2013** 2020-12-23 10:00 UTC
