### ISSUE TITLE
findmitoscaf output - annelid CDS and peptide sequences

### ISSUE THREAD

**Issue by LorenaDerezanin** [linzhi2013/MitoZ#69] opened 2020-07-20 13:27 UTC
Hi Linzhi,
I ran the `findmitoscaf` command to detect potential NUMTs and other contamination in the mitogenome sequence of _Eira barbara_, a mustelid carnivoran (generated with NOVOplasty):
```
$MITOZ/MitoZ.py findmitoscaf --thread_number 10 --genetic_code 2 --clade Chordata \
--outprefix findscf_eira_annot2 \
--fastq1 $READS/adapt_trimmed_R1_val_1.fq.gz \
--fastq2 $READS/adapt_trimmed_R2_val_2.fq.gz \
--fastq_read_length 150 \
--fastafile $MITO/Eira_barbara.fasta
```
The run finished with results dir containing empty high and low abundance files, which leads me to the conclusion that no contaminants have been detected in the mitogenome, would this be correct?

The potential issue lies in the summary.txt containing the info that the most related species to my mustelid is a worm  _Phascolosoma esculenta_, and finding in tmp dir, the cds.taxa.sorted.uniq file lists Annelida species.
The genewise.gff.pep file contains 5 genes (COX1, COX 2, COX3, CYTB, ATP6 ) from 5 annelid species noted in previously mentioned cds.taxa.sorted.uniq file.
Is this perhaps just a regular approach for searching for potential parasite sequence contamination using known parasite nt and aa sequences?

Here's the snapshot from the log file (slurm-194580.out, included in the zipped bundle):
```
A: not found!
2020-07-19 17:41:05
/home/derezanin/miniconda3/envs/mitoz/bin/python3 /home/derezanin/my_software/release_MitoZ_v2.3/bin/findmitoscaf/pick_most_related_sp.py findscf_eira_annot2.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds.taxa findscf_eira_annot2.mitogenome.fa findscf_eira_annot2.most_related_species.txt
```
Besides this message, run finished without errors, exit code 0.

Just for the info, in the `annotate` run I ran two days ago on the same mitogenome input, the most related species was correctly recognized as _Martes martes._. 

Could it be that in the` findmitoscaf`, parameter --clade is not taken into account?
What would be your interpretation?

Here is the result dir with tmp/ included:
[findscf_eira_annot2.result.gz](https://github.com/linzhi2013/MitoZ/files/4947823/findscf_eira_annot2.result.gz)

Thank you,
Lorena

**Comment by linzhi2013** [comment] 2020-07-21 08:17
Hello Lorena,

I couldn't open the file `findscf_eira_annot2.result.gz`. How did you package this file?

After I did `gzip -d findscf_eira_annot2.result.gz`, the result is a single plain file `findscf_eira_annot2.result`. It should be a directory instead.

**Comment by LorenaDerezanin** [comment] 2020-07-21 09:07
Oh sorry, you're right, I automatically ran recursive pigz, which only handles files in subdirs. 
Here's a properly zipped tar:
[findscf_eira_annot2.result.tar.gz](https://github.com/linzhi2013/MitoZ/files/4952381/findscf_eira_annot2.result.tar.gz)

Cheers,
L

**Comment by linzhi2013** [comment] 2020-07-21 11:08
> Oh sorry, you're right, I automatically ran recursive pigz, which only handles files in subdirs.
> Here's a properly zipped tar:
> [findscf_eira_annot2.result.tar.gz](https://github.com/linzhi2013/MitoZ/files/4952381/findscf_eira_annot2.result.tar.gz)
> 
> Cheers,
> L

Hello Lorena,

Go to your `tmp` directory,  check the file `Eira_barbara.fasta`, which was your input file to MitoZ, only ONE sequence in this file (inferred by the `Eira_barbara.fasta.abun.fa` file, because  `Eira_barbara.fasta` is symbliclink to me), and it has high abundance (`>CEira_barbara 576.94 length=16559`), therefore, no sequence will be in `*.low_abundance`.

All the initially potential "mt" sequences are in the file `findscf_eira_annot2.hmmtblout.besthit`, `findscf_eira_annot2.hmmtblout.besthit.sim` and  `findscf_eira_annot2.hmmtblout.besthit.sim.fa`. If you cannot find any other sequences in these files, then there should be no "contaminants" in your `$MITO/Eira_barbara.fasta` file.


Cheers

**Comment by Prunoideae** [comment] 2020-07-21 12:19
Dear Lorena,

> The run finished with results dir containing empty high and low abundance files, which leads me to the conclusion that no contaminants have been detected in the mitogenome, would this be correct?

Yes, no contaminants is *detected* in the mitogenome, but there may be contaminants in the output mitogenome sequences, when those sequences are not left out alone, but contributed to the picked scaffold in previous assembly, it's better to use some tools to do a second check for the output contigs.

> Is this perhaps just a regular approach for searching for potential parasite sequence contamination using known parasite nt and aa sequences?

MitoZ uses a general local protein database to predict what the gene is, at least likely to be, classified into some taxonomic class in the findmitoscaf module. This works for most of the time, but due to the mutation itself is quite of a randomness, some genes are more similar to a somewhat more remote species. Since Phascolosoma esculenta is a worm too large to be a parasite, and it's marine, I would suggest to ignore it.

> Could it be that in the` findmitoscaf`, parameter --clade is not taken into account?

The `--clade` option in `findmitoscaf` module declares that which the profiled Hidden Markov Model (profiled HMM) file is used in the sequences identification by the HMMER. Changing this to other unrelated clades may lead to unreliable predicted PCG completeness in the `findmitoscaf` module, which can affect latter candidate picking. But if you want to apply MitoZ on some clades that have no valid model built-in, you can either build one, or just use the most related clade. Profiled HMM is suitable in even very remote clades, though there are still some loss.

**Comment by LorenaDerezanin** [comment] 2020-07-29 15:52
Thank you both for your time and concise reply!

**Comment by linzhi2013** [comment] 2021-01-21 16:28
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:28 UTC
