### ISSUE TITLE
high_abundance and low_abundance files

### ISSUE THREAD

**Issue by paul-bio-hh** [linzhi2013/MitoZ#104] opened 2021-01-13 01:41 UTC
after annotation when I look up the summary file to find missing genes,

![image](https://user-images.githubusercontent.com/76936761/104394768-9e9eff00-558a-11eb-8aab-8b2f3c1198d7.png)
I might find missing genes from *.high_abundance* and *.low_abundance* files.

so I look up the temp directory
![image](https://user-images.githubusercontent.com/76936761/104395216-97c4bc00-558b-11eb-82cc-037d8e7ad41f.png)

1. so... what kind of file do i have to look?

2. And to find missing genes I should use all2 with --run_mode 3 right?

**Comment by linzhi2013** [comment] 2021-01-13 10:24
https://github.com/linzhi2013/MitoZ

![image](https://user-images.githubusercontent.com/6203542/104439823-db222900-5591-11eb-9d87-80ed7d16133c.png)

**Comment by linzhi2013** [comment] 2021-01-21 16:23
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:23 UTC
