### ISSUE TITLE
question about the result

### ISSUE THREAD

**Issue by willright28** [linzhi2013/MitoZ#88] opened 2020-10-17 05:49 UTC
hi dear @linzhi2013：

I had a issue when I used the MitoZ. I wrote a list containing all the name of my fastq files and run the `MitoZ.py all` with a loop. Normally, result have two directories and it's true for parts of my samples, but  for **some** of samples the outcome only had the intermediate `.tmp` without the final `.result`. ThenI found all the incorrect `.tmp` directory missing the `.annotation` in it, so why some outcoms are normal while others are not ? 

Thanks in advance!

**Comment by willright28** [comment] 2020-10-17 06:12
It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!

**Comment by linzhi2013** [comment] 2020-10-17 14:50
> hi dear @linzhi2013：
> 
> I had a issue when I used the MitoZ. I wrote a list containing all the name of my fastq files and run the `MitoZ.py all` with a loop. Normally, result have two directories and it's true for parts of my samples, but for **some** of samples the outcome only had the intermediate `.tmp` without the final `.result`. ThenI found all the incorrect `.tmp` directory missing the `.annotation` in it, so why some outcoms are normal while others are not ?
> 
> Thanks in advance!

Hello,

which version are you using?

As far as I remember, the 2.3 version creates a 'tmp' directory, which means that when you are doing a loop, the later samples will write into the same 'tmp' directory, I don't know what would happen (unless you delete the 'tmp' directory after each sample, which is what I would recommend).

**Comment by linzhi2013** [comment] 2020-10-17 14:53
> It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!

You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.

I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.

**Comment by willright28** [comment] 2020-10-19 01:21
> > hi dear @linzhi2013：
> > I had a issue when I used the MitoZ. I wrote a list containing all the name of my fastq files and run the `MitoZ.py all` with a loop. Normally, result have two directories and it's true for parts of my samples, but for **some** of samples the outcome only had the intermediate `.tmp` without the final `.result`. ThenI found all the incorrect `.tmp` directory missing the `.annotation` in it, so why some outcoms are normal while others are not ?
> > Thanks in advance!
> 
> Hello,
> 
> which version are you using?
> 
> As far as I remember, the 2.3 version creates a 'tmp' directory, which means that when you are doing a loop, the later samples will write into the same 'tmp' directory, I don't know what would happen (unless you delete the 'tmp' directory after each sample, which is what I would recommend).

My version is 2.4，I will try to use 'all2'.
Thanks for your kindly reply!

**Comment by willright28** [comment] 2020-10-20 06:33
> > It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> > And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!
> 
> You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.
> 
> I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.

Hi dear @linzhi2013 :

For one of my sample, I have tried to use both the 'all' and 'all2' commond to get a result, but the outcome was only `.tmp` still, and missing the `.annotation` directory.
And the ouput said `ALL sequences are low abundance(<10X);CDS_found_lengths_list: 0 `.
Are there something to do with the sample itself ？

Thanks in advance!

**Comment by linzhi2013** [comment] 2020-10-20 09:24
> CDS_found_lengths_list

I think it may fail to assemble the mitochondrial sequences. Please send me the log files (both stdout and stderr)

Thanks

**Comment by willright28** [comment] 2020-10-21 01:46
> > CDS_found_lengths_list
> 
> I think it may fail to assemble the mitochondrial sequences. Please send me the log files (both stdout and stderr)
> 
> Thanks

Please take a look，thanks！

[nohup.txt](https://github.com/linzhi2013/MitoZ/files/5412699/nohup.txt)

**Comment by zzzygolden** [comment] 2020-12-16 06:30
> > > It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> > > And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!
> > 
> > 
> > You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.
> > I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.
> 
> Hi dear @linzhi2013 :
> 
> For one of my sample, I have tried to use both the 'all' and 'all2' commond to get a result, but the outcome was only `.tmp` still, and missing the `.annotation` directory.
> And the ouput said `ALL sequences are low abundance(<10X);CDS_found_lengths_list: 0 `.
> Are there something to do with the sample itself ？
> 
> Thanks in advance!

I also had the same problem and want to know how to resolve it. Thanks!

**Comment by zzzygolden** [comment] 2020-12-16 08:00
> > > It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> > > And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!
> > 
> > 
> > You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.
> > I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.
> 
> Hi dear @linzhi2013 :
> 
> For one of my sample, I have tried to use both the 'all' and 'all2' commond to get a result, but the outcome was only `.tmp` still, and missing the `.annotation` directory.
> And the ouput said `ALL sequences are low abundance(<10X);CDS_found_lengths_list: 0 `.
> Are there something to do with the sample itself ？
> 
> Thanks in advance!

I use 2.4 version and run  the `MitoZ.py all` and have a question similar to yours, the output is  

> All sequences are low abundance (<10X)
CDS_found_lengths_list:  [0]
quick mode got no result!

Should I run it in a different mode? Please tell me your solutions if you succeed! Thanks very much!

**Comment by willright28** [comment] 2020-12-16 08:34
> > > > It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> > > > And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!
> > > 
> > > 
> > > You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.
> > > I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.
> > 
> > 
> > Hi dear @linzhi2013 :
> > For one of my sample, I have tried to use both the 'all' and 'all2' commond to get a result, but the outcome was only `.tmp` still, and missing the `.annotation` directory.
> > And the ouput said `ALL sequences are low abundance(<10X);CDS_found_lengths_list: 0 `.
> > Are there something to do with the sample itself ？
> > Thanks in advance!
> 
> I use 2.4 version and run the `MitoZ.py all` and have a question similar to yours, the output is
> 
> > All sequences are low abundance (<10X)
> > CDS_found_lengths_list:  [0]
> > quick mode got no result!
> 
> Should I run it in a different mode? Please tell me your solutions if you succeed! Thanks very much!

I haven‘t find a solution yet, maybe you could give @linzhi2013 the log file to take a look.

**Comment by zzzygolden** [comment] 2020-12-16 08:39
> > > > > It seems the `--usepre` argument can be used for time saving If I had the clean data in `tmp` directory produced by the last step, right ?
> > > > > And code may be `MitoZ.py all --usepre --fastq1 ./tmp/clean.1.fq.gz --fastq2 ./tmp/clean.2.fq.gz`, please do not hesitate to correct me, thx a lot !!
> > > > 
> > > > 
> > > > You can just use the 'all2' command to do this. Because the 'all2' command won't filter the fq files.
> > > > I'm not quite sure if `--usepre ` works in your case, someone needs to check the codes.
> > > 
> > > 
> > > Hi dear @linzhi2013 :
> > > For one of my sample, I have tried to use both the 'all' and 'all2' commond to get a result, but the outcome was only `.tmp` still, and missing the `.annotation` directory.
> > > And the ouput said `ALL sequences are low abundance(<10X);CDS_found_lengths_list: 0 `.
> > > Are there something to do with the sample itself ？
> > > Thanks in advance!
> > 
> > 
> > I use 2.4 version and run the `MitoZ.py all` and have a question similar to yours, the output is
> > > All sequences are low abundance (<10X)
> > > CDS_found_lengths_list:  [0]
> > > quick mode got no result!
> > 
> > 
> > Should I run it in a different mode? Please tell me your solutions if you succeed! Thanks very much!
> 
> I haven‘t find a solution yet, maybe you could give @linzhi2013 the log file to take a look.

Thanks, maybe I will try a different mode.

**Comment by linzhi2013** [comment] 2021-01-21 16:24
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:24 UTC

**Comment by xuzs-png** [comment] 2024-07-23 02:32
I got the same problem,how did you solve it ?Thanks in advance!
All sequences are low abundance (<10X)
CDS_found_lengths_list:  [0]
quick mode got no result!
