### ISSUE TITLE
No results 

### ISSUE THREAD

**Issue by sstwins21** [linzhi2013/MitoZ#70] opened 2020-07-21 05:06 UTC
Hi,

I am using mitoz to scaffold a mitochondrial genome from New Zealand stick insects and the results came with no results...
This is the parameters I used:

release_MitoZ_v2.4-alpha/MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix axx500 \
--thread_number 12 \
--fastq1 "/scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/data/CLI525_200/CLI525_200_1.fastq" \
--fastq2 "/scale_wlg_nobackup/filesets/nobackup/ga02470/prevent_from_delete/data/CLI525_200/CLI525_200_2.fastq" \
--fastq_read_length 100 \
--insert_size 200  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda'

The run failed and gave only temp file with no results.
When I checked the error messages, it seems that it is not picking up any mitochondrial DNA.
[mitoz.txt](https://github.com/linzhi2013/MitoZ/files/4951426/mitoz.txt)

[mitoz.err.txt](https://github.com/linzhi2013/MitoZ/files/4951429/mitoz.err.txt)

Could you help me what I might have done wrong?
Could it be ele3 library problem?

Kind regards,
Shane

**Comment by linzhi2013** [comment] 2020-07-21 08:39
Hi Shane，

Can you check this file `work71.hmmtblout.besthit.sim.fa` in the `tmp` directory? how many sequences in it and their length ?

According to your `mitoz.err.txt` file, MitoZ report no annotation results. I doubt there might be no sequences in `work71.hmmtblout.besthit.sim.fa`. If that's the case, you can try the MitoZ version 2.3, because the version 2.4-alpha will extract part of the data to do mitogenome assembly, which might not be what you wanted.

And check how much data volume in your `CLI525_200_1.fastq` and `CLI525_200_2.fastq`.

Cheers

**Comment by sstwins21** [comment] 2020-07-21 22:51
Hi,

Thank you so much for your reply. Yes there is work71.hmmtblout.besthit.sim.fa in ./temp/assembly/ directory containing 13 scaffolds. Would the top scaffold be the scaffold from the assembly that contains the mitochondrial genome and the rest would be the different versions of mtDNA?

For the volume of the files, there are in total 2,804,605,088 reads and each of them are 100bp long. Thus the coverage is about 93x which I don't think it would be enough.

Kind regards,
Shane

**Comment by linzhi2013** [comment] 2020-07-22 09:49
> Hi,
> 
> Thank you so much for your reply. Yes there is work71.hmmtblout.besthit.sim.fa in ./temp/assembly/ directory containing 13 scaffolds. Would the top scaffold be the scaffold from the assembly that contains the mitochondrial genome and the rest would be the different versions of mtDNA?
> 
> For the volume of the files, there are in total 2,804,605,088 reads and each of them are 100bp long. Thus the coverage is about 93x which I don't think it would be enough.
> 
> Kind regards,
> Shane

So, the 13 scaffolds in `work71.hmmtblout.besthit.sim.fa` have been filtered out by MitoZ, which were not considered as real mt sequences.

>2,804,605,088 reads and each of them are 100bp long

Therefore, the total volume of data is 280 G bp?? But MitoZ version 2.4-alpha will only extract 5 Gbp for assembly. If this is true, you can ask MitoZ to use more data (say 8 Gbp. not remembering the parameter) for assembly. 2 to 8 Gbp data is enough for mitogenome assembly, and too much data will lead MitoZ to run a very long time.

**Comment by linzhi2013** [comment] 2021-01-21 16:28
I'm closing this. You can reopen it if the problem is still there.

**Closed by linzhi2013** 2021-01-21 16:28 UTC
